sudo: false
addons:
  apt:
    packages:
      - aspell
      - aspell-en
language: perl
perl:
    #- dev
    #- "blead"
    #- stable
    - "5.26"
    - "5.24"
    - "5.22"
env:
  global:
    - RELEASE_TESTING=1
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - cpan-install Sub::Util
  - build-dist
  - cd $BUILD_DIR
install:
  - cpan-install ExtUtils::MakeMaker~6.68 --deps Devel::PPPort
  - cpan-install --coverage
before_script:
  - coverage-setup
script:
  - perl Makefile.PL
  - make
  - prove -b -r -s -j$(test-jobs) $(test-files)
after_success:
  - coverage-report
